version: '3'

services:

  scrapper:
    container_name: scrapper
    build: 
      context: . 
      dockerfile: Dockerfile
    command:  bash start.sh 
    network_mode: host
    # ports:
    #        - 6800:6800
    restart: always
    depends_on: 
        - postgres

  postgres:
    build:
      context: . 
      dockerfile: Dockerfile.psql
    container_name: postgres
    environment:
       POSTGRES_PASSWORD: dB$A5Be?&^5q
       POSTGRES_DB: eva_db
    network_mode: host
    # ports:
    #   - 5432:5432
    restart: always
